<?php
if($table==="hopeman"){
	define("DBH","dbs3.seas.rochester.edu");
	define("DBU","arduino");
	define("DBP","read_arduino");
	define("DBN","arduino");
	define("Arduino_IP","10.4.136.202");
}
if($table==="cogen"){
	define("DBH","dbs3.seas.rochester.edu");
	define("DBU","arduino");
	define("DBP","read_arduino");
	define("DBN","arduino");
	define("Arduino_IP","10.4.159.133");
}
?>
